### PR TITLE
Updated to latest hawkular versions

### PR DESCRIPTION
**Pull request by garethahealy**
Lots of changes to get client to latest hawkular versions. A few tests fail, which i've raised issues for. Will try and work on those some more if you happy with these updates

### CODE REVIEW

**Comment by pilhuhn** [comment]
Cool, thanks for the effort!

**Comment by garethahealy** [comment]
Verified CI tests work via:
- mvn -s .travis.maven.settings.xml verify -Dwildfly.logging.console.level=DEBUG -B -Pci

Seems travis is using demo.hawkular.com as its endpoint. Not sure what version that is, thus if tests failing is a false-positive?

**Comment by garethahealy** [comment]
Looking into tenants test failure on travis, the following is returned via cURL:

`localhost:hawkular-client-java garethah$ curl -u jdoe:password -X GET "http://demo.hawkular.org/hawkular/metrics/tenants" -H "Content-Type: application/json" -H "Hawkular-Tenant: travis-ci"
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>`

I dont think the URL is wrong, so presume http://demo.hawkular.org is at fault.

**Comment by vnugent** [comment]
@garethahealy the CI instances behind demo.hawkular.org and livingontheedge.hawkular.org were running the older hawkular app.  I'm going to replace them with hawkular-services.

**Comment by garethahealy** [comment]
Made lots of changes to metrics. Its now compliant with the hawkular server and has unit tests to check basic functionality.

Will start to update alerts next so that is working against latest as well

**Comment by garethahealy** [comment]
Updated alerts as well to v1.1.2.

Is this PR OK to be merged? since its now quite large. Will raise other PRs to update metrics to 0.19 and update inventory to latest.

**Comment by pilhuhn** [comment]
@garethahealy While I have no (real) objections merging this, I am irritated by the failing travis build.

**Comment by garethahealy** [comment]
@pilhuhn as per @vnugent comment, its due to the endpoint which travis uses hosting an old version of the metrics. I am happy for you to wait until @vnugent has updated http://demo.hawkular.org to the latest services release.

**Comment by pilhuhn** [comment]
Ok, I see - I read his comment as if he did that already. 
I'll merge and then we go from there.

**Comment by pilhuhn** [comment]
Thanks @garethahealy for your huge effort.

**Comment by garethahealy** [comment]
No worries. I'll raise a PR for the inventory changes in a few days as well.

**Comment by vnugent** [comment]
I just realize I don't have write access to the travis-ci job[*] to update HAWKULAR_ENDPOINT env. We don't have enough compute resources to host both demo and livingontheedge.  @pilhuhn if you have access please make the change as follows HAWKULAR_ENDPOINT=http://livingontheedge.hawkular.org  

travis-ci job
https://travis-ci.org/hawkular/hawkular-client-java

**Pull request merged**
