### PR TITLE
Added alerts api support

### PR DESCRIPTION
**Pull request by jkandasa**
@vnugent I have added alerts api support. Kindly review and merge it

### CODE REVIEW

**Comment by jkandasa** [comment]
Ticket: Add support for Alert API #15

**Comment by jkandasa** [comment]
@vnugent Does [Hawkular Demo](http://demo.hawkular.org) server update to date?

**Comment by FilipB** [comment]
Just a few general comments:
- some javadoc and comments would be definitely nice
- is there any reason not to log anything?
- not sure if this is doable everywhere but it's recommended to fix the code rather than using SuppressWarnings("unchecked")

**Comment by jkandasa** [comment]
@FilipB Thank you for your valuable feedback!
- Yes, We will add javadoc, I have added a ticket to track: https://github.com/Hawkular-QE/hawkular-java-client/issues/28
- We are using `slf4j.Logger` for main code https://github.com/jkandasa/hawkular-java-client/blob/master/src/main/java/org/hawkular/client/ClientResponse.java#L116 and for Test `Reporter.log` https://github.com/Hawkular-QE/hawkular-java-client/pull/26/files#diff-13879768ef5ecd0c98a9d2e48b3f7c87R116
- `SuppressWarnings("unchecked")` Yes, this not good but in some cases unable to avoid.

**Comment by vnugent** [comment]
Can you add the failing tests to the known-failure group, eg `@Test(groups={"known-failure"})`?

**Comment by jkandasa** [comment]
@vnugent marked alerts failure test cases with `@Test(groups={"known-failure"})`

**Comment by vnugent** [comment]
@jkandasa can you pull and rebase new changes I added to master? test in travis should pass with the new known-failure exclusion

**Pull request merged**
